name: CI/CD for Python & React

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Python Setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install -r backend/requirements.txt

      - name: Run Python tests
        run: |
          .\venv\Scripts\activate
          pytest

      # React Setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install React dependencies
        run: |
          cd frontend
          if (Test-Path -Path node_modules) { Remove-Item -Recurse -Force node_modules }
          if (Test-Path -Path package-lock.json) { Remove-Item -Force package-lock.json }
          if (Test-Path -Path build) { Remove-Item -Recurse -Force build }
          npm install

      - name: Build React App
        run: |
          cd frontend
          npm run build

      # Zip the Build Directory
      - name: Zip Build Folder
        run: |
          Compress-Archive -Path frontend\build\* -DestinationPath build-artifacts\react-build.zip

      # Upload as Artifact (Optional)
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build-artifacts\react-build.zip

      # Commit and Push Build Zip to Repo
      - name: Commit and Push Build Zip
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add build-artifacts/react-build.zip
          git commit -m "Add React build zip"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deployment (Optional)
      - name: Deploy Application
        run: echo "Deployment Successful!"
