name: CI/CD for Python & React

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Changed from ubuntu-latest to windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Python Setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install -r backend/requirements.txt

      - name: Run Python tests
        run: |
          .\venv\Scripts\activate
          pytest

      # React Setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install React dependencies
        run: |
          cd frontend
          if (Test-Path -Path node_modules) { Remove-Item -Recurse -Force node_modules }
          if (Test-Path -Path package-lock.json) { Remove-Item -Force package-lock.json }
          if (Test-Path -Path build) { Remove-Item -Recurse -Force build }
          npm install

      - name: Build React App
        run: |
          cd frontend
          npm run build

      - name: Store Build Artifacts
        run: |
          New-Item -ItemType Directory -Path build-artifacts -Force
          Copy-Item -Recurse -Path frontend\build\* -Destination build-artifacts\

      # Deployment (Optional)
      - name: Deploy Application
        run: echo "Deployment Successful!"
