name: CI/CD for Python & React

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Python Setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Run Python tests
        run: |
          source venv/bin/activate
          pytest

      # React Setup
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install React dependencies
        run: |
          cd frontend
          rm -rf node_modules package-lock.json  # Ensure a clean slate
          npm install

      - name: Build React App
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            npm run build
          else
            echo "Frontend folder not found!"
          fi


      # Deployment (Optional)
      - name: Deploy Application
        run: echo "Deployment Successful!"
